<?xml version="1.0" ?>
<grid>
  <HMCparameters>
    <StartTrajectory>0</StartTrajectory>
    <Trajectories>100</Trajectories>
    <MetropolisTest>false</MetropolisTest>
    <NoMetropolisUntil>0</NoMetropolisUntil>
    <PerformRandomShift>false</PerformRandomShift>
    <StartingType>TepidStart</StartingType>
    <Seed>643801</Seed>
    <MD>
      <name>
        <elem>OMF2_5StepV</elem>
        <elem>OMF2_5StepV</elem>
        <elem>OMF4_11StepV</elem>
      </name>
      <MDsteps>1</MDsteps>
      <trajL>0.75</trajL>
      <lvl_sizes>
        <elem>9</elem>
        <elem>1</elem>
        <elem>1</elem>
      </lvl_sizes>
    </MD>
  </HMCparameters>
</grid>
